// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wicahxledyeiuixxpguk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpY2FoeGxlZHllaXVpeHhwZ3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTMyMTgsImV4cCI6MjA2MDcyOTIxOH0.YWv-sldyIKfgpGWtYCoKKD1SjQS_mXSfnBeMGIhGOyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);